-- DBeaver 등에서 DB 선택 후 실행 (models.User / db.ensure_users_table 과 동일)
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(80) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(100) NULL,
  email VARCHAR(120) NULL,
  phone VARCHAR(30) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(100) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(120) NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR(30) NULL;


COMMIT;